server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/payflow
    username: payflow
    password: payflow_secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-processor
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    listener:
      auto-startup: false

services:
  risk:
    url: http://localhost:8084
  account:
    url: http://localhost:8082
  ledger:
    url: http://localhost:8083

logging:
  level:
    com.payflow: INFO
